### ISSUE TITLE
Einfacher Selenium Test ohne TestLib

### ISSUE THREAD

**Issue by BenediktSt** [AtosReferenzApplikation/e2e-testing#11]
## Beschreibung
Um die Interaktion mit Web Applikationen zu lernen, soll Selenium Webdriver verwendet werden, um eine Web App im Browser zu steuern. Dabei soll zu Beginn nur ein Selenium Test mit eigenen Mitteln umgesetzt und noch nicht in die TestLib integriert werden.

## Akzeptanzkriterien
* Es existiert ein Test, welcher die Addition auf Folgender Website testet: http://juliemr.github.io/protractor-demo/
* Im Test werden die Selenium Methoden verwendet, um mit der Website zu interagieren
* Die Tests können lokal in einem Browser der Wahl ausgeführt werden

**Comment by Jonathan-Br** [comment]
Implementiert.
