### ISSUE TITLE
Selenium Test mit der der Testlib

### ISSUE THREAD

**Issue by BenediktSt** [AtosReferenzApplikation/e2e-testing#13]
# Beschreibung
Zuletzt soll die TestLib noch mit dem Selenium Test kombiniert werden. Die einzelnen Steps innerhalb des Selenium tests, sollen nun auch alle durch die TestLib abgedeckt werden können

# Akzeptanzkriterien:
* Die Auswahl eines Elements im Selenium Test wird durch die TestLib abgedeckt
* Das Eingeben im Selenium Test wird durch die TestLib abgedeckt
* Die Prüfungen im Selenium Test werden durch die TestLib abgedeckt

**Comment by Jonathan-Br** [comment]
Implementiert.
