### ISSUE TITLE
Umsetzen der zu testenden Anwendung in Java

### ISSUE THREAD

**Issue by BenediktSt** [AtosReferenzApplikation/e2e-testing#4]
## Beschreibung
Das Testframework soll anhand einer kleinen Demo-App aufgebaut werden. Diese Demo-App ist ein kleiner einfacher Taschenrechner. Dieser soll zuerst als eine Java-Klasse umgesetzt werden.

## Akzeptanzkriterien
- Es steht ein Taschenrechner als Java-Klasse zur Verfügung
- Der Taschenrechner benötigt kein grafisches Interface
- Der Taschenrechner besitzt zwei Eingabefelder
- Der Taschenrechner ermöglicht es zwischen 5 Rechenoperationen zu wählen
  - Addition, Subtraktion, Multiplikation, Division, Modulo
- Der Taschenrechner hat eine Funktion zum ausführen der Rechenoperation auf Basis der beigen übergebenen Zahlen
- Ein Umfangreiches Error Handling ist nicht notwendig

**Comment by BenediktSt** [comment]
vergleichbar von der Methodik mit:
http://juliemr.github.io/protractor-demo/
wird auch im Laufe der Einarbeitung später noch verwendet

**Comment by Jonathan-Br** [comment]
"Der Taschenrechner benötigt kein grafisches Interface"
"Der Taschenrechner besitzt zwei Eingabefelder"
Kein grafisches Interface würde für mich bedeuten, dass es eine Kommandozeilenanwendung ist, aber dann hat sie ja keine Eingabefelder sondern lediglich Parameter. Wie ist das zu verstehen?

**Comment by BenediktSt** [comment]
Also Eingabefelder ist hier Recht flexibel gemeint, Parameter sind komplett ausreichend

**Comment by BenediktSt** [comment]
Ein CLI an sich muss auch nicht umgesetzt werden, es reicht wenn die Klasse per Unit Tests gesteuert werden kann

**Comment by Jonathan-Br** [comment]
Sollte über Parameter funktionieren, bin mir allerdings nicht über die Anforderungen für Unit Tests im Klaren.

**Comment by BenediktSt** [comment]
Hast du schon Erfahrung mit Unit-Tests?
Die Anforderung klingt jetzt eventuell komplizierter als man denkt, alles was damit gemeint ist, dass dein Taschenrechner auf irgend eine weise in einem Testfall angesprochen werden kann, so wie eine reale Applikation durch Tests angesprochen werden kann.
Wie das aktuell passiert, ist noch komplett dir überlassen und wird erst später relevant
