### ISSUE TITLE
Aufsetzen von Unit Tests zum Testen der Demo-App

### ISSUE THREAD

**Issue by BenediktSt** [AtosReferenzApplikation/e2e-testing#5]
## Beschreibung
Neben der Applikation selbst sind noch Tests notwendig, welche die kleine Demo-App testen. Dabei sollen sich diese Stück für Stück mit den Funktionen des Testframeworks wachsen. Zu Beginn soll mit einem einfachen Unit Test gestartet werden.

## Akzeptanzkriterien
- Es existiert jeweils ein Unit Test pro Rechenoperation des Taschenrechners
- Der Unit Test kann die bestehenden Methoden des Taschenrechners direkt verwenden

**Comment by Jonathan-Br** [comment]
Habe im Branch Testing etwas gepusht, aber so wie es mir scheint, müsste man eine Instanz der Library nutzen, wenn man das Referenzobjekt in einer anderen Methode festlegen will, als in den Eingaben/Überprüfungen. Kommt mir etwas seltsam vor - Kommentare?

**Comment by BenediktSt** [comment]
Also:
1. Wenn ich das richtig sehe hast du Junit 5 verwendet. Ist ok, ich war nur etwas überrascht und wahrscheinlich wirst du im Projekt eher auf Junit 4 treffen
2. An sich denke ich ist das schon einmal super für Schritt eins und ich bin doch überrascht, wie schnell du das umgesetzt hast
3. Die verwendeten Methoden sollten noch etwas voneinander getrennt werden

``tl.waehle_aus(new Taschenrechner());`` würde ich durch eine eigene Methode ersetzen ``tl.starteAnwendung(new Taschenrechner());``
und 
``tl.gibEin("operation", "+");`` würde ich dann mit der wähle aus methode Umsetzen. Ich denke das ergibt dann alles noch etwas mehr Sinn, wenn wir den Selenium mit ins Bot holen, warum hier ein kleiner Unterscheid besteht.

**Comment by BenediktSt** [comment]
Sonst sieht das schon sehr gut aus, wenn du noch die Kleinigkeit in dem Pull Request des Taschenrechners raus nimmst, dann kannst du den PR gleich auf machen. Dann kann ich noch ein paar Kleinigkeiten direkt dort anmerken

**Comment by Jonathan-Br** [comment]
Habe es jetzt auf JUnit 4 geändert und die gewünschten Änderungen durchgeführt. :)
